#!/usr/bin/env ansible-playbook -i hosts --become -c paramiko
---


- name: Ansible Playbook for reproducibly configuring my Raspberry Pi
  hosts: webservers
  # roles:
  #   - pi
  remote_user: pi

  tasks:
    - name: General Setup
      include: tasks/general.yml
    - name: Setup Pi Hole
      include: tasks/pihole.yml
    - name: Setup Git Config
      include: tasks/git.yml
    - name: Setup Backup HDD and other backup scripts
      include: tasks/backup.yml
