- name: Install some packages for mounting drive, etc.
  become: True
  apt:
    name:
      - exfat-fuse
      - ntfs-3g
      - lsof  # Useful to see what's using the disk, when trying to unmount
      - adb

- name: Mount up backup disk by UUID
  become: True
  ansible.posix.mount:
    path: /mnt/backup-drive
    src: UUID="5E51-4654"
    fstype: exfat
    # x-systemd.device-timeout=15 Don't wait too long to mount while booting
    opts: defaults,auto,users,rw,nofail,umask=000,x-systemd.device-timeout=15
    state: mounted

- name: Create mount point
  file:
    path: /home/pi/code/
    state: directory

- name: Clone sync-rpi repo
  git:
    repo: git@github.com:punchagan/sync-rpi.git
    dest: /home/pi/code/sync-rpi
    version: main
    accept_hostkey: yes
    key_file: /home/pi/.ssh/id_rsa

- name: Clone adb-sync repo
  git:
    repo: git@github.com:google/adb-sync.git
    dest: /home/pi/code/adb-sync
    version: master
    accept_hostkey: yes
    key_file: /home/pi/.ssh/id_rsa

- name: Create symbolic link to adb-sync in /usr/local/bin
  become: True
  file:
    src: "/home/pi/code/adb-sync/adb-sync"
    dest: "/usr/local/bin/adb-sync"
    state: link

- name: Ensure phone backup runs every 4 hours
  ansible.builtin.cron:
    name: "sync phone"
    minute: "15"
    hour: "*/4"
    # FIXME: These URLs would change on each new setup of healthchecks.  This
    # would need to be changed manually.  One idea could be to put the sqlite
    # DB on the backup disk, and use it from there. If that drive is mounted,
    # we are always running the manually setup version of the DB.
    job: "/home/pi/code/sync-rpi/phone.sh > /home/pi/code/sync-rpi/logs.txt && curl -fsS --retry 5 -o /dev/null http://localhost:8000/ping/5e8b989c-3a69-41fc-b59e-5ce4abd984fb"
