- name: Creates an entry for PATH on top of crontab
  ansible.builtin.cron:
    name: PATH
    env: yes
    job: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games:/snap/bin
