---
- name: create pihole group
  become: True
  group:
    name: pihole
    state: present
  register: pihole_group

- name: create pihole user
  become: True
  user:
    name: pihole
    group: pihole
    groups: pihole,www-data
    comment: "ad filtering DNS proxy"
    system: True
    shell: "/usr/sbin/nologin"
    state: present
  when: pihole_group is changed

- name: create pihole configuration directory
  become: True
  file:
    name: /etc/pihole
    state: directory
    owner: pihole
    group: pihole
    mode: 0755
  when: pihole_group is changed

- name: "Download Pi-Hole Installer"
  get_url:
    url: https://install.pi-hole.net
    dest: /tmp/install-pihole.sh
    mode: 0740
  when: pihole_group is changed

- name: Create pihole configuration
  become: True
  template:
    src="setupVars.conf.j2"
    dest="/etc/pihole/setupVars.conf"
    owner=root
    group=root
    mode=0644
  tags: pihole
  when: pihole_group is changed

- name: Install Pi-Hole
  shell: "/tmp/install-pihole.sh --unattended"
  register: dbg_install_pihole
  tags: pihole
  when: pihole_group is changed

# FIXME: Do we need to setup crontab updates for the PiHole ad data?
